In [10]:
library(ArchR)
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ tibble  3.3.0     ✔ purrr   0.3.4
✔ tidyr   1.1.4     ✔ dplyr   1.1.4
✔ readr   2.1.1     ✔ forcats 1.0.0

Warning message:
“package ‘forcats’ was built under R version 4.1.3”
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::arrange()    masks plyr::arrange()
✖ dplyr::between()    masks data.table::between()
✖ dplyr::collapse()   masks IRanges::collapse()
✖ dplyr::combine()    masks gridExtra::combine(), Biobase::combine(), BiocGenerics::combine()
✖ purrr::compact()    masks plyr::compact()
✖ dplyr::count()      masks plyr::count(), matrixStats::count()
✖ dplyr::desc()       masks plyr::desc(), IRanges::desc()
✖ tidyr::expand()     masks Matrix::expand(), S4Vectors::expand()
✖ tidyr::extract()    masks magrittr::extract()
✖ dplyr::failwith()   masks plyr::failwith()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::first()      masks data.table::first(), S4Vectors::first()
✖ dplyr::id()         masks plyr::id()
✖ dplyr::lag()        masks stats::lag()
✖ dplyr::last()       masks data.table::last()
✖ dplyr::mutate()     masks plyr::mutate()
✖ tidyr::pack()       masks Matrix::pack()
✖ ggplot2::Position() masks BiocGenerics::Position(), base::Position()
✖ purrr::reduce()     masks GenomicRanges::reduce(), IRanges::reduce()
✖ dplyr::rename()     masks plyr::rename(), S4Vectors::rename()
✖ purrr::set_names()  masks magrittr::set_names()
✖ dplyr::slice()      masks IRanges::slice()
✖ dplyr::summarise()  masks plyr::summarise()
✖ dplyr::summarize()  masks plyr::summarize()
✖ purrr::transpose()  masks data.table::transpose()
✖ tidyr::unpack()     masks Matrix::unpack()

In [3]:
markersPeaks <- readRDS('/lustre/scratch125/casm/teams/team215/users/od5/projects/celltherapy/ipsc/multiome/archr/tf_pilot/batch1/ipsc/archr_DARs_perturbation_obj.rds')

In [4]:
markersPeaks

class: SummarizedExperiment
dim: 82350 10
metadata(2): MatchInfo Params
assays(7): Log2FC Mean ... AUC MeanBGD
rownames(82350): 1 2 ... 82349 82350
rowData names(4): seqnames idx start end
colnames(10): CEBPA CEBPD ... TBX21 TCF7
colData names(0):

In [18]:
markerList <- getMarkers(markersPeaks, cutOff = "FDR <= 0.2")

In [19]:
markerList

markerPeaks_df <- Reduce(bind_rows,lapply(1:length(markerList), function(i) {
  ## Cell type or state
  ct <- names(markerList)[i]
  ## Object of marker peaks
  gr <- markerList[[i]]
  if (nrow(gr) == 0) {
    return(NULL)
  } else {
     ## Getting peak names and stats
    peaks <- data.frame(chr=as.character(gr$seqnames), 
                        start=gr$start,
                        end=gr$end,
                        Log2FC=gr$Log2FC,
                        FDR=gr$FDR,
                        MeanDiff=gr$MeanDiff,
                        Cell_type=ct,
                        stringsAsFactors = F) %>%
      mutate(peak=paste0(chr, ':',start, '-',end))
    return(peaks)
  }
}))

List of length 10
names(10): CEBPA CEBPD Control EBF1 FOXO3 HOPX PRDM1 RUNX2 TBX21 TCF7

In [31]:
markerPeaks_df[order(markerPeaks_df$Log2FC, decreasing=T),]

     chr   start     end       Log2FC    FDR          MeanDiff   Cell_type
6    chr5  123180084 123180584 6.978755  1.215980e-05 0.5107302  RUNX2
4    chr1  224623733 224624233 6.728430  1.215980e-05 0.4287242  RUNX2
1    chr7   76054083  76054583 6.712435  5.603769e-03 0.2984721  CEBPD
10   chr9  127519294 127519794 6.712263  8.460351e-05 0.4239013  RUNX2
107  chr11  44569048  44569548 6.620674  3.445321e-03 0.3975754  RUNX2
38   chr9   79765420  79765920 6.506863  1.163630e-03 0.3671073  RUNX2
67   chr20  61861370  61861870 6.404024  1.993559e-03 0.3415689  RUNX2
47   chr15  67201084  67201584 6.403450  1.619819e-03 0.3414314  RUNX2
48   chr17   4176358   4176858 6.327041  1.619819e-03 0.3236083  RUNX2
5    chr4  139950552 139951052 6.327037  1.215980e-05 0.3236074  RUNX2
13   chr16  83143731  83144231 6.242974  2.027006e-04 0.3050591  RUNX2
119  chr5  142215750 142216250 6.178974  3.445321e-03 0.2916449  RUNX2
160  chr5  131825356 131825856 6.149049  4.590361e-03 0.2855741  RUNX2
153  chr16  89619819  89620319 6.137822  4.590361e-03 0.2833287  RUNX2
86   chr11  35593085  35593585 6.130761  2.663526e-03 0.2819255  RUNX2
46   chr11  45383062  45383562 6.122993  1.619819e-03 0.2803896  RUNX2
85   chr11  34302359  34302859 6.098535  2.663526e-03 0.2756076  RUNX2
309  chr19  42553294  42553794 6.088224  1.223416e-02 0.2736159  RUNX2
88   chr5  168404387 168404887 6.053516  2.663526e-03 0.2670149  RUNX2
66   chr20  44702782  44703282 6.041915  1.993559e-03 0.2648436  RUNX2
324  chr8  116231240 116231740 6.037180  1.223416e-02 0.2639624  RUNX2
250  chr8   93985712  93986212 6.031405  8.993004e-03 0.2628915  RUNX2
196  chr2  229154279 229154779 5.992679  6.453582e-03 0.2558206  RUNX2
252  chr8  130375985 130376485 5.962909  8.993004e-03 0.2505124  RUNX2
245  chr4  166527413 166527913 5.959532  8.993004e-03 0.2499172  RUNX2
65   chr2  224395949 224396449 5.930563  1.993559e-03 0.2448679  RUNX2
64   chr15  89052519  89053019 5.909105  1.993559e-03 0.2411926  RUNX2
161  chrX   68868279  68868779 5.900281  4.590361e-03 0.2396969  RUNX2
89   chr6  168007571 168008071 5.871774  2.663526e-03 0.2349272  RUNX2
302  chr10  63554587  63555087 5.863906  1.223416e-02 0.2336273  RUNX2
⋮    ⋮     ⋮         ⋮         ⋮         ⋮            ⋮          ⋮
3265 chr20  37543699  37544199 -5.159977 0.187917491  -0.1418474 RUNX2
1862 chr5   14665104  14665604 -5.171202 0.105372250  -0.1429873 RUNX2
675  chr8   38540971  38541471 -5.177749 0.031640808  -0.1436562 RUNX2
1794 chr18   5570573   5571073 -5.189428 0.105372250  -0.1448570 RUNX2
1448 chr7  132380037 132380537 -5.204227 0.079060766  -0.1463927 RUNX2
2350 chr1  205477020 205477520 -5.206404 0.142891981  -0.1466199 RUNX2
641  chr15  76439513  76440013 -5.208946 0.031640808  -0.1468856 RUNX2
3302 chr5   17145949  17146449 -5.223623 0.187917491  -0.1484294 RUNX2
468  chr1   33338356  33338856 -5.264132 0.023457598  -0.1527724 RUNX2
3258 chr2   37105089  37105589 -5.272822 0.187917491  -0.1537200 RUNX2
826  chr5   94573283  94573783 -5.287570 0.044494050  -0.1553414 RUNX2
2465 chr5  135997901 135998401 -5.338939 0.142891981  -0.1611201 RUNX2
817  chr20   6908754   6909254 -5.343406 0.044494050  -0.1616325 RUNX2
300  chr1  212909952 212910452 -5.347398 0.012234156  -0.1620916 RUNX2
635  chr13  40317513  40318013 -5.385431 0.031640808  -0.1665306 RUNX2
801  chr16   5466458   5466958 -5.399275 0.044494050  -0.1681756 RUNX2
1035 chr19  13934040  13934540 -5.427552 0.059699982  -0.1715853 RUNX2
1090 chr7   69608875  69609375 -5.443505 0.059699982  -0.1735384 RUNX2
788  chr1  163596797 163597297 -5.455937 0.044494050  -0.1750757 RUNX2
489  chr2  238096482 238096982 -5.482317 0.023457598  -0.1783818 RUNX2
1925 chr9  116800904 116801404 -5.483166 0.105372250  -0.1784891 RUNX2
158  chr4   92256750  92257250 -5.492394 0.004590361  -0.1796607 RUNX2
1873 chr5  138461474 138461974 -5.505062 0.105372250  -0.1812812 RUNX2
1396 chr20  44617896  44618396 -5.579696 0.079060766  -0.1911228 RUNX2
513  chr6   76120143  76120643 -5.592311 0.023457598  -0.1928372 RUNX2
674  chr7  119100767 119101267 -5.596309 0.031640808  -0.1933836 RUNX2
1036 chr19  15170330  15170830 -5.619748 0.059699982  -0.1966180 RUNX2
492  chr21  42927604  42928104 -5.724892 0.023457598  -0.2117913 RUNX2
304  chr10 117442909 117443409 -5.833481 0.012234156  -0.2286668 RUNX2
407  chr9  121386417 121386917 -5.866826 0.017153946  -0.2341089 RUNX2
     peak
6    chr5:123180084-123180584
4    chr1:224623733-224624233
1    chr7:76054083-76054583
10   chr9:127519294-127519794
107  chr11:44569048-44569548
38   chr9:79765420-79765920
67   chr20:61861370-61861870
47   chr15:67201084-67201584
48   chr17:4176358-4176858
5    chr4:139950552-139951052
13   chr16:83143731-83144231
119  chr5:142215750-142216250
160  chr5:131825356-131825856
153  chr16:89619819-89620319
86   chr11:35593085-35593585
46   chr11:45383062-45383562
85   chr11:34302359-34302859
309  chr19:42553294-42553794
88   chr5:168404387-168404887
66   chr20:44702782-44703282
324  chr8:116231240-116231740
250  chr8:93985712-93986212
196  chr2:229154279-229154779
252  chr8:130375985-130376485
245  chr4:166527413-166527913
65   chr2:224395949-224396449
64   chr15:89052519-89053019
161  chrX:68868279-68868779
89   chr6:168007571-168008071
302  chr10:63554587-63555087
⋮    ⋮
3265 chr20:37543699-37544199
1862 chr5:14665104-14665604
675  chr8:38540971-38541471
1794 chr18:5570573-5571073
1448 chr7:132380037-132380537
2350 chr1:205477020-205477520
641  chr15:76439513-76440013
3302 chr5:17145949-17146449
468  chr1:33338356-33338856
3258 chr2:37105089-37105589
826  chr5:94573283-94573783
2465 chr5:135997901-135998401
817  chr20:6908754-6909254
300  chr1:212909952-212910452
635  chr13:40317513-40318013
801  chr16:5466458-5466958
1035 chr19:13934040-13934540
1090 chr7:69608875-69609375
788  chr1:163596797-163597297
489  chr2:238096482-238096982
1925 chr9:116800904-116801404
158  chr4:92256750-92257250
1873 chr5:138461474-138461974
1396 chr20:44617896-44618396
513  chr6:76120143-76120643
674  chr7:119100767-119101267
1036 chr19:15170330-15170830
492  chr21:42927604-42928104
304  chr10:117442909-117443409
407  chr9:121386417-121386917

In [23]:
markerPeaks_df

     chr   start     end       Log2FC     FDR          MeanDiff    Cell_type
1    chr7   76054083  76054583  6.712435  5.603769e-03  0.2984721  CEBPD
2    chr1   33099239  33099739  4.986931  3.334459e-06  0.6204648  RUNX2
3    chr1   24964880  24965380  5.319872  4.743871e-06  0.4516259  RUNX2
4    chr1  224623733 224624233  6.728430  1.215980e-05  0.4287242  RUNX2
5    chr4  139950552 139951052  6.327037  1.215980e-05  0.3236074  RUNX2
6    chr5  123180084 123180584  6.978755  1.215980e-05  0.5107302  RUNX2
7    chr8    1059445   1059945  4.852633  1.215980e-05  0.4235607  RUNX2
8    chr5     957270    957770  3.514641  1.305799e-05  0.3963807  RUNX2
9    chr2  196292241 196292741  3.589609  6.809663e-05  0.4306855  RUNX2
10   chr9  127519294 127519794  6.712263  8.460351e-05  0.4239013  RUNX2
11   chr11  20027054  20027554 -3.265160  1.181279e-04 -0.5201867  RUNX2
12   chr6  158653526 158654026  3.993290  2.021117e-04  0.2854353  RUNX2
13   chr16  83143731  83144231  6.242974  2.027006e-04  0.3050591  RUNX2
14   chr10 104328040 104328540  3.883416  2.119507e-04  0.4943827  RUNX2
15   chr17  39757819  39758319  5.064127  2.119507e-04  0.3138896  RUNX2
16   chr17  81094733  81095233  3.273816  2.119507e-04  0.4869830  RUNX2
17   chr7  140252853 140253353  3.846515  2.119507e-04  0.4640890  RUNX2
18   chr10  59387832  59388332  4.226765  2.559255e-04  0.3466430  RUNX2
19   chr17  79281179  79281679  4.811895  3.286739e-04  0.3551868  RUNX2
20   chr7  151428443 151428943  3.298803  3.286739e-04  0.4135302  RUNX2
21   chr6    7758464   7758964  3.579420  4.253572e-04  0.2869469  RUNX2
22   chr8  125941990 125942490  3.796893  4.253572e-04  0.4591512  RUNX2
23   chr5   65861896  65862396  4.616941  5.476364e-04  0.3592298  RUNX2
24   chr16  70700024  70700524  2.909220  5.506954e-04  0.2310452  RUNX2
25   chr19  38213713  38214213  2.992120  6.325329e-04  0.3839472  RUNX2
26   chr1   68323202  68323702  5.299812  7.065640e-04  0.2921926  RUNX2
27   chr3  125141318 125141818  3.294482  7.065640e-04  0.4239852  RUNX2
28   chr16  85969481  85969981  3.435943  7.406878e-04  0.4906773  RUNX2
29   chr13  50678346  50678846  4.221757  7.552474e-04  0.3316401  RUNX2
30   chr5    7779253   7779753  4.768865  7.722298e-04  0.3239176  RUNX2
⋮    ⋮     ⋮         ⋮         ⋮          ⋮            ⋮           ⋮
3393 chr19  10888500  10889000  1.4096885 0.194063676   0.13261507 RUNX2
3394 chr6   27375046  27375546 -0.9462694 0.194063676  -0.12365876 RUNX2
3395 chr17  57338559  57339059  2.1720852 0.195137363   0.12210571 RUNX2
3396 chr12 104216052 104216552 -2.9663749 0.196060868  -0.22380229 RUNX2
3397 chr4  113979391 113979891 -0.1769694 0.196060868  -0.02477254 RUNX2
3398 chr1  234772227 234772727  1.4305435 0.196210672   0.13462360 RUNX2
3399 chr7    4883613   4884113 -1.4473951 0.197600594  -0.47433090 RUNX2
3400 chr2  219433813 219434313 -2.2067496 0.198518193  -0.19267537 RUNX2
3401 chr12 122399418 122399918  1.5503942 0.198964716   0.11874180 RUNX2
3402 chr16  68645036  68645536 -1.1033316 0.199670617  -0.14111833 RUNX2
3403 chr4  173522481 173522981 -2.3308458 0.199798254  -0.16470093 RUNX2
3404 chr6    6547314   6547814  2.5684509 0.199798254   0.13800544 RUNX2
3405 chr4  139592941 139593441  2.6431617 0.004578057   0.23103045 TBX21
3406 chr2   65579673  65580173  1.8730816 0.009514413   0.28348608 TBX21
3407 chr3  143805406 143805906  1.5779546 0.036487434   0.13425981 TBX21
3408 chr16  72128502  72129002  4.5563260 0.080979402   0.20639211 TBX21
3409 chr1    7608771   7609271  3.1635639 0.083017025   0.16365080 TBX21
3410 chr11  15622355  15622855  2.0225766 0.083017025   0.10772173 TBX21
3411 chr3  120421151 120421651  3.1052864 0.086360071   0.09917431 TBX21
3412 chr5  126591490 126591990 -3.0380382 0.088929234  -0.17410244 TBX21
3413 chr1   48500501  48501001  2.4447215 0.147318911   0.19194053 TBX21
3414 chr15  92123917  92124417  1.5138037 0.147318911   0.19612607 TBX21
3415 chr2    8254153   8254653  3.3223060 0.147318911   0.10065294 TBX21
3416 chr15  24690604  24691104  1.9339800 0.152814618   0.19253790 TBX21
3417 chr15  26720515  26721015  2.4043599 0.152814618   0.14131747 TBX21
3418 chr18  63102847  63103347  4.2021589 0.152814618   0.09065762 TBX21
3419 chr4   16694621  16695121  2.5854318 0.152814618   0.09948480 TBX21
3420 chr1  214439742 214440242  4.9241446 0.159398880   0.06734161 TBX21
3421 chr4  146179958 146180458  4.2092886 0.159398880   0.13550047 TBX21
3422 chr2  217862958 217863458  3.3623377 0.182127769   0.11508990 TBX21
     peak
1    chr7:76054083-76054583
2    chr1:33099239-33099739
3    chr1:24964880-24965380
4    chr1:224623733-224624233
5    chr4:139950552-139951052
6    chr5:123180084-123180584
7    chr8:1059445-1059945
8    chr5:957270-957770
9    chr2:196292241-196292741
10   chr9:127519294-127519794
11   chr11:20027054-20027554
12   chr6:158653526-158654026
13   chr16:83143731-83144231
14   chr10:104328040-104328540
15   chr17:39757819-39758319
16   chr17:81094733-81095233
17   chr7:140252853-140253353
18   chr10:59387832-59388332
19   chr17:79281179-79281679
20   chr7:151428443-151428943
21   chr6:7758464-7758964
22   chr8:125941990-125942490
23   chr5:65861896-65862396
24   chr16:70700024-70700524
25   chr19:38213713-38214213
26   chr1:68323202-68323702
27   chr3:125141318-125141818
28   chr16:85969481-85969981
29   chr13:50678346-50678846
30   chr5:7779253-7779753
⋮    ⋮
3393 chr19:10888500-10889000
3394 chr6:27375046-27375546
3395 chr17:57338559-57339059
3396 chr12:104216052-104216552
3397 chr4:113979391-113979891
3398 chr1:234772227-234772727
3399 chr7:4883613-4884113
3400 chr2:219433813-219434313
3401 chr12:122399418-122399918
3402 chr16:68645036-68645536
3403 chr4:173522481-173522981
3404 chr6:6547314-6547814
3405 chr4:139592941-139593441
3406 chr2:65579673-65580173
3407 chr3:143805406-143805906
3408 chr16:72128502-72129002
3409 chr1:7608771-7609271
3410 chr11:15622355-15622855
3411 chr3:120421151-120421651
3412 chr5:126591490-126591990
3413 chr1:48500501-48501001
3414 chr15:92123917-92124417
3415 chr2:8254153-8254653
3416 chr15:24690604-24691104
3417 chr15:26720515-26721015
3418 chr18:63102847-63103347
3419 chr4:16694621-16695121
3420 chr1:214439742-214440242
3421 chr4:146179958-146180458
3422 chr2:217862958-217863458